management:
 endpoint:
   info:
     enabled: true  
   health:
     enabled: true
   shutdown:
     enabled: true
 endpoints:
    web:
      exposure:
        include: "*"
message: Ola git teste mirandinha
musicapp:
  id: ${random.int[1,100]}
server:
  port: 0
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:sqlite:MyMusic.db
    username: ""
    password: ""
    driver-class-name:  org.sqlite.JDBC
    database-platform: com.dojo.musicas.config.SQLiteDialect
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000